### ISSUE TITLE
Won't let me remove associated Discord account

### ISSUE THREAD

**Issue by CyraFen** [discourse/discourse-plugin-discord-auth#10]
I changed the email on my Discord account a few months ago and I wanted my profile to reflect the new change by removing it and relogging on with it. Not sure if this is an issue with Discourse itself or the plugin, but when I go into my settings I am unable to remove my associated discord account. Since it is possible with my Twitter account, I'm assuming it should also be possible with my Discord account? I'm also not the admin of the site (Pokemon Insurgence Forums forums.p-insurgence.com) so I'm not sure if there is something wrong with the site itself, on my end, or with the plugin. Apologies if this is an error on my end!

![image](https://user-images.githubusercontent.com/25874350/59952852-ab5d7e80-944b-11e9-8aa5-ee7d9ca715ed.png)

**Comment by featheredtoast** [comment]
Definitely not you; It's an issue with the plugin - there should be an enhancement to allow this, as this has been changed in recent Discourse versions.

**Comment by featheredtoast** [comment]
Fixed here: https://github.com/discourse/discourse-plugin-discord-auth/commit/8159929aa3c7a6fb4bc9e7155c80186ee3df4ce1
