### ISSUE TITLE
Discord email is not verified when logging in

### ISSUE THREAD

**Issue by nightkr** [discourse/discourse-plugin-discord-auth#2]
# Repro

1. Install/enable/set up this plugin
2. Create a Discord user with the email address of a friend with a Discourse account
3. Log in with that Discord account

# Result

You are now logged into your friend's Discourse account.

# Expected result

Access is declined, since Discord confirmation email was never clicked.

**Comment by featheredtoast** [comment]
Ouch. I'll be disabling trusting email auth until this is fixed upstream. Thanks for catching this!

**Comment by featheredtoast** [comment]
After digging in and looking at the "trusted" option, it seems to do more with account creation verification than logging into an existing account.

This is definitely best fixed upstream. I'll keep this issue open to track it in the meantime.

**Comment by nightkr** [comment]
I submitted a patch to upstream at adaoraul/omniauth-discord#14.

**Comment by nightkr** [comment]
Given that there is still no response from the upstream, do you know if it's possible to make Discourse load the patched gem from Git?

**Comment by featheredtoast** [comment]
I've tried it before but I don't think that's possible with way the plugin dependencies are loaded currently - it assumes that it's loading from a proper rubygem release.

**Comment by featheredtoast** [comment]
I just got a response from the maintainer, he's going to get this released soon.

**Comment by nightkr** [comment]
Upstream patch has been merged and released as 0.1.8!

**Comment by featheredtoast** [comment]
whoa that took a time... Once the version is up on rubygems, I'll update this. Thanks for the heads up!

**Comment by featheredtoast** [comment]
Fixed in https://github.com/featheredtoast/discourse-plugin-discord-auth/commit/9bc759a5d06820a27e643533ae0c413a32735f11

Thanks for reporting!
