### ISSUE TITLE
::DiscordAuthenticator should define an `enabled?` function. Patching for now.

### ISSUE THREAD

**Issue by OvermindDL1** [discourse/discourse-plugin-discord-auth#8]
Keep getting this spammed into my log like 12 times every time anyone view the login panel.  Looks like a simple enough fix however.  :-)

**Comment by featheredtoast** [comment]
Just made a fix for this, sorry about that. There was just a new interface change that needed to be implemented here.

**Comment by OvermindDL1** [comment]
Awesome, thanks much!  I appreciate the work!  :-)
